<?php

return [
    'makhana-4-suta' => [
        'name' => '4 Suta Makhana',
        'category' => 'Makhana',
        'image' => 'uploads/products/makhana-4-suta.jpg',
        'badge' => 'Premium',
        'sku' => 'MAK-004',
        'description' => 'Carefully selected premium fox nuts with a consistent size, ideal for retail and bulk requirements.',
        'packaging' => '250gm, 500gm, 1kg, Bulk',
        'moq' => '100 KG',
    ],
    'makhana-5-suta' => [
        'name' => '5 Suta Makhana',
        'category' => 'Makhana',
        'image' => 'uploads/products/makhana-5-suta.jpg',
        'badge' => 'Best Seller',
        'sku' => 'MAK-005',
        'description' => 'Uniform-sized premium makhana with excellent crunch, suitable for retail, wholesale and export orders.',
        'packaging' => '250gm, 500gm, 1kg, Bulk',
        'moq' => '100 KG',
    ],
    'makhana-6-suta' => [
        'name' => '6 Suta Makhana',
        'category' => 'Makhana',
        'image' => 'uploads/products/makhana-6-suta.jpg',
        'badge' => 'Premium',
        'sku' => 'MAK-006',
        'description' => 'Large-sized premium fox nuts with a light crunch, ideal for premium retail and export requirements.',
        'packaging' => '250gm, 500gm, 1kg, Bulk',
        'moq' => '100 KG',
    ],
    'aloo-bhujia' => [
        'name' => 'Aloo Bhujia',
        'category' => 'Namkeen',
        'image' => 'uploads/products/aloo-bhujia.jpg',
        'badge' => 'Popular',
        'sku' => 'NAM-001',
        'description' => 'A classic, crispy potato and gram-flour snack with an authentic savoury flavour.',
        'packaging' => '200gm, 400gm, 1kg, Bulk',
        'moq' => '100 KG',
    ],
    'mix-namkeen' => [
        'name' => 'Mix Namkeen',
        'category' => 'Namkeen',
        'image' => 'uploads/products/mix-namkeen.jpg',
        'badge' => 'Popular',
        'sku' => 'NAM-002',
        'description' => 'A delicious mix of crunchy ingredients, made for everyday snacking and retail shelves.',
        'packaging' => '200gm, 400gm, 1kg, Bulk',
        'moq' => '100 KG',
    ],
    'khatta-meetha' => [
        'name' => 'Khatta Meetha',
        'category' => 'Namkeen',
        'image' => 'uploads/products/khatta-meetha.jpg',
        'badge' => 'Popular',
        'sku' => 'NAM-003',
        'description' => 'A balanced sweet and tangy namkeen with a satisfying crunch for every occasion.',
        'packaging' => '200gm, 400gm, 1kg, Bulk',
        'moq' => '100 KG',
    ],
];
